version: "3"
services:
  app:
    container_name: charlesmartino
    restart: always
    build:
      context: .
      args:
        - MONGO_URL=mongodb://mongo:27017/charlesmartino
        - REDIS_HOST=redis
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: "mongo:4"
    ports:
      - "27018:27017"
  redis:
    container_name: redis
    image: "redis:4.0.11"
    ports:
      - "6379:6379"
